name: ci

on:
  push:
    branches: [ main ]

jobs:
  main:
    runs-on: ubuntu-latest
    container: epitechcontent/epitest-docker
    steps:
    
      - name: Check Out Repo 
        uses: actions/checkout@v2